# Generated by Django 2.2.12 on 2021-11-27 16:59

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=60)),
                ('LastName', models.CharField(max_length=60)),
                ('phoneNumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True)),
                ('Email', models.EmailField(max_length=254)),
                ('passwd', models.CharField(max_length=60)),
                ('userId', models.CharField(max_length=30, unique=True)),
            ],
        ),
    ]
